AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a Bucket with public read access.
Parameters:
    BucketName:
      Type: String
      Description: Bucket name
Resources:
  PublicS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PublicS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: 's3:GetObject'
            Effect: Allow
            Principal: '*'
            Resource: !Sub arn:aws:s3:::${BucketName}/*
